name: Linting Generated Boilerplate Project code

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Install Dependencies
        run: go mod download

  framework_matrix:
    needs: install_dependencies
    strategy:
      matrix:
        framework:
          [chi, echo, fiber, gin, gorilla/mux, httpRouter, standard-library]
        goVersion: ["1.22"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goVersion }}
      - name: build templates
        run: go run main.go create -t ${{ matrix.framework }} -f ${{ matrix.framework}}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: ${{ matrix.framework }}
          args: --timeout=5m