name: Linting

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0